exense/step-frontend

projects/step-frontend/src/lib/angularjs/js/app.js
projects/step-frontend/src/lib/angularjs/js/controllers/planEditor.js
projects/step-frontend/src/lib/angularjs/js/controllers/plans.js
projects/step-frontend/src/lib/angularjs/js/export.js
projects/step-frontend/src/lib/angularjs/partials/exportDialog.html
projects/step-frontend/src/lib/angularjs/partials/importDialog.html
projects/step-frontend/src/lib/modules/_common/services/export-dialogs.service.ts
projects/step-frontend/src/lib/modules/_common/services/import-dialogs.service.ts
projects/step-frontend/src/lib/modules/function/components/function-list/function-list.component.ts
projects/step-frontend/src/lib/modules/parameter/parameters-list/parameters-list.component.ts
projects/step-frontend/src/lib/modules/plan/components/plan-list/plan-list.component.ts

Disabling recursive exports by default / added progress message

SED-1022 improve import export dialogs

---

projects/step-core/src/lib/pipes/dashboard-link.pipe.ts
projects/step-core/src/lib/services/dashboard.service.ts
projects/step-core/src/lib/step-core.module.ts
projects/step-frontend/src/lib/modules/scheduler/scheduled-task-list/scheduled-task-list.component.ts

Fixes https://exense.atlassian.net/browse/SED-1161
Also contains pipe that is not currently used but will replace function call when migrating to NG2+

SED-1161 infinite loop grafana

---

projects/step-frontend/src/lib/modules/_common/components/sidebar/sidebar.component.ts

after merging 
https://github.com/exense/step-frontend/pull/103
and
https://github.com/exense/step-frontend/pull/101
FE does not compile due to non existend `.subscribe()`method on ILocationService
https://github.com/exense/step-frontend/blob/master/projects/step-frontend/src/lib/modules/_common/components/sidebar/sidebar.component.ts#L27

SED-1298 ILocationService vs Location

---

projects/step-app/src/styles.scss
projects/step-core/src/lib/modules/table/pipe/bulk-operation-label.pipe.ts
projects/step-core/src/lib/modules/table/services/bulk-operations-invoke.service.ts

Small naming changes to make operations more clear

SED-1281 Fixed naming for bulk operations

---

projects/step-core/styles/components/_step-sidebar.scss

SED-1315 set max width for tenant chooser

---

projects/step-core/src/lib/modules/table/components/table/table.component.html
projects/step-core/src/lib/modules/table/components/table/table.component.scss
projects/step-core/src/lib/modules/table/components/table/table.component.ts
projects/step-core/src/lib/modules/table/directives/additional-header.directive.ts
projects/step-frontend/src/lib/modules/function/components/function-list/function-list.component.html
projects/step-frontend/src/lib/modules/function/components/function-list/function-list.component.scss
projects/step-frontend/src/lib/modules/function/services/function-dialogs.service.ts
projects/step-frontend/src/lib/modules/parameter/parameters-list/parameters-list.component.html
projects/step-frontend/src/lib/modules/plan/components/plan-list/plan-list.component.html
projects/step-frontend/src/lib/modules/scheduler/scheduled-task-list/scheduled-task-list.component.html

I chose a generic solution, which was in my optinion the most elegant, so that multiple table-headers are allowed and any combination of them can be combined optionally.

Sed 1365 unify headers

---

projects/step-core/src/lib/directives/tooltip-immediate-close.directive.ts
projects/step-core/src/lib/step-core.module.ts

Check the issue's description for details

SED-1409 Tooltip not disappearing on mouseover

---

projects/step-frontend/src/lib/angularjs/partials/components/resourceInput.html

As suggested field was made as readonly

SED-1411 Creating a resource using a file path leads to issues

---

projects/step-core/src/lib/modules/basics/services/auth.service.ts
projects/step-frontend/src/lib/modules/_common/components/login/login.component.ts
projects/step-frontend/src/lib/modules/_common/interceptors/auth.interceptor.ts

Same PR as SED-1578 login view is not showing error messages but for 3.20

SED-1578 login view is not showing error messages 320

---

projects/step-core/src/lib/modules/tree/services/tree-state.service.ts
projects/step-frontend/src/lib/modules/plan/components/plan-tree-editor/plan-tree-editor.component.ts
projects/step-frontend/src/lib/modules/plan/services/artefacts-clipboard.token.ts

Also contains SED-1711 Copy node from one plan to another is not working anymore

SED-1712 Treeview: copying node and then pasting it multiple times doesn't work

---

projects/step-core/src/lib/modules/tree/services/tree-state.service.ts
projects/step-frontend/src/lib/modules/plan/components/plan-tree-editor/plan-tree-editor.component.ts

Draw tree and artifact's tree model were out of sync.
To fix it operations on the same parent's children should be performed at once.

SED-1733 Operation on multiple selection in visual plan editor doesn't work anymore

---

projects/step-core/src/lib/modules/table/shared/table-remote-data-source.ts

SED-1904 Navigating back to Execution of TestSet causes empty output

---

projects/step-core/src/lib/modules/dynamic-forms/components/dynamic-field-group-editor/dynamic-field-group-editor.component.ts

Check detailed explanation in JIRA

SED-1905 Optional inputs vanish when empty

---

projects/step-core/src/lib/directives/focusable.directive.ts
projects/step-core/src/lib/directives/focusables.directive.ts
projects/step-core/src/lib/directives/recursive-tab-index.directive.ts
projects/step-core/src/lib/directives/trap-focus.directive.ts
projects/step-core/src/lib/modules/basics/components/date-filter/date-filter.component.ts
projects/step-core/src/lib/modules/tree/services/tree-state.service.ts
projects/step-core/src/lib/services/persistence.service.ts
projects/step-core/src/lib/services/view-registry.service.ts
projects/step-core/src/lib/shared/persistence-tokens.ts
projects/step-core/src/lib/shared/storage.token.ts
projects/step-core/src/lib/step-core.module.ts
projects/step-core/styles/_core-variables.scss
projects/step-core/styles/components/_step-inputs.scss
projects/step-frontend/src/lib/modules/plan/components/plan-tree-editor/plan-tree-editor.component.ts
projects/step-frontend/src/lib/modules/timeseries/performance-view/filter-bar/filter-bar.component.ts
projects/step-frontend/src/lib/modules/timeseries/performance-view/filter-bar/item/filter-bar-item.component.html
projects/step-frontend/src/lib/modules/timeseries/performance-view/filter-bar/item/filter-bar-item.component.scss
projects/step-frontend/src/lib/modules/timeseries/performance-view/filter-bar/item/filter-bar-item.component.ts

V3.22.0 branch switch

---

projects/step-core/src/lib/components/plan-tree/plan-tree.component.scss
projects/step-frontend/src/lib/modules/execution/components/execution-tree/execution-tree.component.html
projects/step-frontend/src/lib/modules/execution/components/execution-tree/execution-tree.component.scss

SED-1957 Big execution trees are not readable (#410)

---

projects/step-core/src/lib/modules/basics/components/array-filter/array-filter.component.ts
projects/step-core/src/lib/modules/table/components/custom-search-dropdown/custom-search-dropdown.component.html

* SED-2357 Selected keyword type not displayed when navigating back to keyword list
* SED-2357 Fix dropdowns for custom columns

SED-2357 Selected keyword type not displayed when navigating back to keyword list

---

projects/step-core/src/lib/modules/basics/components/array-filter-advanced/array-filter-advanced.component.html
projects/step-core/src/lib/modules/basics/components/array-filter-advanced/array-filter-advanced.component.ts
projects/step-core/src/lib/modules/basics/step-basics.module.ts
projects/step-core/src/lib/modules/table/services/filter-condition-factory.service.ts
projects/step-core/src/lib/modules/table/shared/array-filter-condition.ts
projects/step-core/src/lib/modules/table/shared/filter-condition-type.enum.ts
projects/step-frontend/src/lib/modules/execution/components/execution-list/execution-list.component.html
projects/step-frontend/src/lib/modules/execution/components/execution-step/execution-step.component.ts
projects/step-frontend/src/lib/modules/execution/components/keyword-calls/keyword-calls.component.html
projects/step-frontend/src/lib/modules/execution/components/keyword-calls/keyword-calls.component.ts

Note advanced is used since we only solve it partly for the 24.2 release to limit changes

SED-2861 filters-based-on-combo-selection-should-use-or-clause

---

projects/step-core/styles/components/_theme-config.scss

https://exense.atlassian.net/browse/SED-2850

SED-2850 fix dropdowns styles

---

projects/step-frontend/src/lib/modules/automation-packages/components/automation-packages-list/automation-packages-list.component.html
projects/step-frontend/src/lib/modules/automation-packages/components/automation-packages-list/automation-packages-list.component.scss
projects/step-frontend/src/lib/os-plugins/modules/function-packages/components/function-package-list/function-package-list.component.html
projects/step-frontend/src/lib/os-plugins/modules/function-packages/components/function-package-list/function-package-list.component.scss
projects/step-frontend/src/lib/os-plugins/modules/function-packages/components/upload-package-btn/upload-package-btn.component.html
projects/step-frontend/src/lib/os-plugins/modules/function-packages/components/upload-package-btn/upload-package-btn.component.scss

https://exense.atlassian.net/browse/SED-2843

SED-2843 add class making border radius

---

projects/step-frontend/src/lib/modules/timeseries/chart/time-series-chart.component.ts
projects/step-frontend/src/lib/modules/timeseries/performance-view/table/timeseries-table.component.ts

fixed in both 24 and 25 branches

SED-2890-fix issue

---

projects/step-frontend/src/lib/modules/timeseries/modules/_common/components/time-range-picker/time-range-picker.component.ts

* SED-2993-fix incorrect time selection
* SED-2993-use 23:59:59 for end date

Sed 2993 incorrect custom time range selection (#785)

---

projects/step-core/src/lib/components/artefact-details/artefact-details.component.html
projects/step-core/src/lib/components/artefact-details/artefact-details.component.scss

https://exense.atlassian.net/browse/SED-3020

SED-3020 set icon styles on conditions

---

projects/step-core/src/lib/pipes/extract-query-params.pipe.ts
projects/step-core/src/lib/pipes/extract-url.pipe.ts
projects/step-core/src/lib/step-core.module.ts
projects/step-frontend/src/lib/modules/bookmarks/components/manage-bookmarks-list/manage-bookmarks-list.component.html

https://exense.atlassian.net/browse/SED-3088

SED-3088 add extract pipes

---

projects/step-core/src/lib/modules/bookmarks/injectables/bookmark.service.ts

Fix multiple bookmarks requests issue reported by Lucian

SED-3130 Fix multiple table requests issue

---

projects/step-frontend/src/lib/modules/_common/components/sidebar/sidebar.component.scss

https://exense.atlassian.net/browse/SED-3124

SED-3124 allign settings icon

---

projects/step-frontend/src/lib/modules/_common/shared/status.enum.ts
projects/step-frontend/src/lib/modules/execution/services/execution-list-filter-interceptor.service.ts

https://exense.atlassian.net/browse/SED-3240

SED-3240 add missing options

---

projects/step-frontend/src/lib/modules/admin/components/screen-configuration-list/screen-configuration-list.component.ts
projects/step-frontend/src/lib/modules/admin/components/screen-input-edit-dialog/screen-input-edit-dialog.component.ts

https://exense.atlassian.net/browse/SED-3245

SED-3245 set position for new inputs

---

projects/step-frontend/src/lib/modules/report-nodes/components/report-node/report-node.component.ts

https://exense.atlassian.net/browse/SED-3230

SED-3230 add artefactId to query

---

projects/step-core/src/lib/modules/keywords-common/components/agent-token-selection-criteria/agent-token-selection-criteria.component.html
projects/step-core/src/lib/modules/keywords-common/components/agent-token-selection-criteria/agent-token-selection-criteria.component.scss
projects/step-core/src/lib/modules/scheduler-common/components/edit-scheduler-task-dialog/edit-scheduler-task-dialog.component.html
projects/step-core/src/lib/modules/scheduler-common/components/edit-scheduler-task-dialog/edit-scheduler-task-dialog.component.scss
projects/step-frontend/src/lib/modules/function/components/function-configuration-dialog/function-configuration-dialog.component.html
projects/step-frontend/src/lib/modules/function/components/function-configuration-dialog/function-configuration-dialog.component.scss

https://exense.atlassian.net/browse/SED-3285

SED-3285 redesign advanced

---

projects/step-core/src/lib/components/artefact-details/artefact-details.component.html
projects/step-core/src/lib/components/artefact-details/artefact-details.component.scss
projects/step-core/src/lib/components/reference-artefact-name/reference-artefact-name.component.html
projects/step-core/src/lib/components/reference-artefact-name/reference-artefact-name.component.scss
projects/step-core/src/lib/components/reference-artefact-name/reference-artefact-name.component.ts

PR already approved (recreated based on Step 26)

SED-3391 plan-editor-does-not-allow-to-set-dynamic-names-for-call-keyword-and-call-plan-components-2
